name: Hello World Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: 23f3001743@ds.study.iitm.ac.in
        run: echo "Hello, world!"
